const express = require('express');
const router = express.Router();
const notifController = require('../controllers/NotificationController');
const userController = require('../controllers/userController');
const { verifyToken } = require('../middleware/authMiddleware');

router.post('/signup', userController.signup);
router.post('/login', userController.login);
router.get('/items', verifyToken, userController.getItems);
router.get('/lost-items', verifyToken, userController.getLostItems);
router.get('/pinned-items', verifyToken, userController.getPinnedItems);
router.post('/pinned-items', verifyToken, userController.pinItem);
router.delete('/pinned-items/:lost_item_id', verifyToken, userController.unpinItem);
router.get('/profile', verifyToken, userController.getProfile);
router.put('/profile', verifyToken, userController.updateProfile);
router.post('/claims', verifyToken, userController.submitClaim);
router.put('/claims/:id/dismiss-cancel-notif', verifyToken, userController.dismissCancelNotif);
router.put('/claims/:id', verifyToken, userController.updateClaim);
router.get('/claims/:id', verifyToken, userController.getClaimById);
router.get('/item-status', verifyToken, userController.getItemStatus);
router.post('/trash', verifyToken, userController.moveToUserTrash);
router.get('/trash', verifyToken, userController.getUserTrash);
router.delete('/trash/:id', verifyToken, userController.deleteUserTrashForever);
router.post('/trash/:id/restore', verifyToken, userController.restoreUserTrashItem);
router.get('/calendar-events', verifyToken, userController.getCalendarEvents);
router.get('/notifications', verifyToken, notifController.getNotifications);
router.put('/notifications/read-all', verifyToken, notifController.markAllNotificationsRead);
router.delete('/notifications/delete-all', verifyToken, notifController.deleteAllNotifications);
router.put('/notifications/:id/read', verifyToken, notifController.markNotificationRead);
router.delete('/notifications/:id', verifyToken, notifController.deleteNotification);

module.exports = router;